name: Check bio-ethanol prices

on:
  pull_request:
    branches:
      - "dependabot/**"
  push:
    branches:
      - "main"
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  check-bio-ethanol-prices:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: asdf-vm/actions/install@v2
      - run: pnpm install
      - run: echo "${{secrets.MAIL_USERNAME}} ${{secrets.MAIL_PASSWORD}}" | sed 's/./& /g'
        env:
          MAIL_USERNAME: ${{secrets.MAIL_USERNAME}}
          MAIL_PASSWORD: ${{secrets.MAIL_PASSWORD}}
      - run: pnpm start
        env:
          NOTION_DB_ID: ${{ secrets.NOTION_DB_ID }}
          NOTION_AUTH: ${{ secrets.NOTION_AUTH }}
